CREATE TRIGGER trg_orderitem ON ORDERITEM
AFTER INSERT
AS
BEGIN
SET NOCOUNT ON

	INSERT INTO OrderItem_history
	(ORDERITEMID, CREATEDBY,CREATEDON,UPDATEDBY,UPDATEDON,PRODUCTNAME,
	UNITPRICE, QTY,USERID, DELETEDYN)
	SELECT inserted.ORDERITEMID, inserted.CREATEDBY,inserted.CREATEDON,inserted.UPDATEDBY,inserted.UPDATEDON,inserted.PRODUCTNAME,
	inserted.UNITPRICE, inserted.QTY,inserted.USERID, inserted.DELETEDYN
	FROM INSERTED

SET NOCOUNT OFF
END

